import AboutComponent from './AboutComponent'
import { Container } from '../components/shared/Container/Container'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'About',
    description: 'Generated by create next app',
}

export default function About() {
    return (
        <Container>
            <AboutComponent></AboutComponent>
        </Container>
    )
}
