import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Header } from './components/shared/Header/Header'
import { Footer } from './components/shared/Footer/Footer'
import { cookies } from 'next/headers'

const cookieName = process.env.LOGIN_COOKIE_NAME || 'loginSession'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: { default: 'The Blog', template: '%s | The Blog' },
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    async function checkLogin() {
        const cookieStore = await cookies()
        return Boolean(cookieStore.get(cookieName)?.value)
    }

    const isUserLogged = await checkLogin()

    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">
                <Header isUserLogged={isUserLogged} />
                {children}
                <Footer />
            </body>
        </html>
    )
}
